### ISSUE TITLE
Week 6

### ISSUE THREAD

**Issue by msgritsenko** [ASKYI/-staff-time#8]
- [x]  Разные представления для разных задач на уровне WPF
- [x]  Общая часть: вкладка, календарь, область для работ
- [x]  При двойном клике на задачу создаётся работа в текущий день.
- [x]  Переход по календарю
- [x]  В базу данных наполнить тестовые работы (sql с применением функции получения текущей даты)
- [x]  Ознакомиться с Perfect Forwarding c++

**Comment by alyona-chur** [comment]
При клике по кнопке создается работа
